### ISSUE TITLE
clean based themes: favoriteicon to the complete right of the viewport

### ISSUE THREAD

**Issue by lucaboesch** [academic-moodle-cooperation/moodle-blocks_semester_sortierung#3]
In clean based themes (tested in Moodle 2.7.7) the star to vote for favorites goes far to the right hand side, even to the right of the right menu bar.
I think, absolute position is not an ideal solution.

I handled a workaround, adding this style. 

``` css
.block_semester_sortierung .no_javascript .semester .favoriteicon,
.block_semester_sortierung .semester.nosemester .favoriteicon,
.block_semester_sortierung .semester.expanded .favoriteicon{
    float: right!important;
    margin-top: -24px!important; 
    position: relative!important;
}
```

You may want to look into the issue.

Best regards.
